---
- name: Check all hosts
  hosts: all
  become: true
  any_errors_fatal: true
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Show hostname
      ansible.builtin.command: hostname
      changed_when: false
