---
- name: Join additional control plane nodes
  hosts: control_plane:!control_plane[0]
  become: true
  any_errors_fatal: true
  tasks:
    - name: Check if node already joined
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join control plane
      ansible.builtin.command: "{{ hostvars[first_control_plane].control_plane_join_command }}"
      when: not kubelet_conf.stat.exists
      no_log: true
