---
- name: Fetch kubeconfig
  hosts: control_plane[0]
  become: true
  any_errors_fatal: true
  tasks:
    - name: Fetch admin kubeconfig
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ lookup('env', 'CLUSTER_KUBECONFIG_DEST') }}"
        flat: true

- name: Fix kubeconfig server endpoint locally
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ansible_become: false
  tasks:
    - name: Replace server endpoint with VIP
      ansible.builtin.replace:
        path: "{{ lookup('env', 'CLUSTER_KUBECONFIG_DEST') }}"
        regexp: 'server: https://.*:[0-9]+'
        replace: 'server: https://{{ api_vip }}:{{ api_port }}'
