---
- name: Fetch kubeconfig
  hosts: control-01
  become: true
  tasks:
    - name: Fetch admin kubeconfig
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: /home/louis/IaC-Kubernetes/kubeconfig
        flat: true

- name: Fix kubeconfig server endpoint locally
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ansible_become: false
  tasks:
    - name: Replace server endpoint with VIP
      ansible.builtin.replace:
        path: /home/louis/IaC-Kubernetes/kubeconfig
        regexp: 'server: https://.*:6443'
        replace: 'server: https://{{ api_vip }}:{{ api_port }}'
