[loadbalancer]
lb-01 ansible_host=10.200.50.145
lb-02 ansible_host=10.200.50.146

[control_plane]
control-01 ansible_host=10.200.50.151
control-02 ansible_host=10.200.50.152
control-03 ansible_host=10.200.50.153

[worker]
worker-01 ansible_host=10.200.50.161
worker-02 ansible_host=10.200.50.162

[k8s_cluster:children]
control_plane
worker

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/louis/.ssh/id_ed25519_k8s_lab
ansible_become=true
ansible_ssh_common_args='-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
